---
# tasks file for ansible-role-prometheus-node-exporter
- name: download node_exporter
  get_url:
    url: "{{ url_download }}"
    dest: /tmp/{{ tarball }}
    checksum: sha256:{{ node_exporter_sha256 }}

- name: create dir {{ prom_dir }}
  file:
    path: "{{ prom_dir }}"
    state: directory
    mode: 0755

- unarchive:
    src: /tmp/{{ tarball }}
    dest: /tmp/
    remote_src: yes

- copy:
    src: /tmp/{{ untar_dir }}/node_exporter
    dest: "{{ prom_dir }}/node_exporter"
    owner: root
    group: root
    mode: 0755
    remote_src: yes

- name: configure service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0755

- name: start and enable node_exporter service
  systemd:
    daemon_reload: yes
    name: node_exporter
    state: started
    enabled: True

